# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OneDriveSDK' do
    pod 'ADAL', :git => "https://github.com/lai001/azure-activedirectory-library-for-objc.git", :tag => "1.2.10"
    pod 'Base32', '~> 1.1'
end

target 'OneDriveSDKTests' do
    pod 'OCMock'
end

